"""add budget_id to expenses

Revision ID: 34e1de35a34f
Revises: 29d5662ec5b7
Create Date: 2026-04-17 16:29:19.330271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34e1de35a34f'
down_revision: Union[str, Sequence[str], None] = '29d5662ec5b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('budget_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'expenses', 'budgets', ['budget_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_column('expenses', 'budget_id')
    # ### end Alembic commands ###
